2023-01-25 20:50:43,407 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-01-25 20:50:44,554 [INFO ]  Rasa server is up and running.
2023-01-25 20:56:20,661 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-01-25 20:56:24,068 [INFO ]  Loading model models/20230125-205103-curious-quarter.tar.gz...
2023-01-25 20:56:26,080 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 20:56:29,922 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 20:57:19,049 [WARNI]  The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2023-01-25 20:57:28,562 [INFO ]  Rasa server is up and running.
2023-01-25 20:58:41,502 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-103' coro=<AsyncServer._handle_event_internal() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py:506> exception=AttributeError("'list' object has no attribute 'setdefault'")>
Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 508, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 542, in _trigger_event
    ret = await handler(*args)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/socketio.py", line 268, in handle_message
    await on_new_message(message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in handler
    await app.ctx.agent.handle_message(message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/agent.py", line 420, in handle_message
    return await self.processor.handle_message(  # type: ignore[union-attr]
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 149, in handle_message
    await self._run_prediction_loop(message.output_channel, tracker)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 774, in _run_prediction_loop
    should_predict_another_action = await self._run_action(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 909, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 801, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 817, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 236, in send_response
    await self.send_custom_json(recipient_id, message.pop("custom"), **message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/socketio.py", line 121, in send_custom_json
    json_message.setdefault("room", recipient_id)
AttributeError: 'list' object has no attribute 'setdefault'
2023-01-25 20:59:51,823 [ERROR]  Encountered an exception while running action 'action_mostrar_entidades'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/action.py", line 741, in run
    response: Any = await self.action_endpoint.request(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 173, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"dictionary update sequence element #0 has length 8; 2 is required","request_body":{"next_action":"action_mostrar_entidades","sender_id":"10b2f0a51cea4bb6832237eab369bcf1","tracker":{"sender_id":"10b2f0a51cea4bb6832237eab369bcf1","slots":{"user_name":"jorge","pokemon_name":"magnemite","pokemon_type":"es de los tipos: electric y steel.","abilities_num":"Tiene 3 habilidades","pokemon_abilities":"magnet-pull, sturdy y analytic.","counter":0,"requested_slot":null,"session_started_metadata":null},"latest_message":{"intent":{"name":"extraer_entidad","confidence":0.9984897375106812},"entities":[{"start":0,"end":26,"text":"ma\\u00f1ana a las 5 de la tarde","value":"2023-01-26T17:00:00.000-03:00","confidence":1.0,"additional_info":{"values":[{"value":"2023-01-26T17:00:00.000-03:00","grain":"hour","type":"value"}],"value":"2023-01-26T17:00:00.000-03:00","grain":"hour","type":"value"},"entity":"time","extractor":"DucklingEntityExtractor"}],"text":"ma\\u00f1ana a las 5 de la tarde","message_id":"4bf1d57d8cb24beeae7e12b08d5edc32","metadata":{},"text_tokens":[[0,6],[7,8],[9,12],[13,14],[15,17],[18,20],[21,26]],"intent_ranking":[{"name":"extraer_entidad","confidence":0.9984897375106812},{"name":"buscar_pokemon","confidence":0.0009006547625176609},{"name":"despedida","confidence":0.0004401695914566517},{"name":"faq","confidence":9.167664393316954e-5},{"name":"intent_pokemon_name","confidence":6.61602898617275e-5},{"name":"saludo","confidence":1.159783005277859e-5}],"response_selector":{"all_retrieval_intents":["faq"],"default":{"response":{"responses":[{"text":"Soy Pok\\u00e9bot y estoy preparado para ser tu nueva Pokedex \\ud83d\\udcbb"}],"confidence":0.9998846054077148,"intent_response_key":"faq\\/quien_eres","utter_action":"utter_faq\\/quien_eres"},"ranking":[{"confidence":0.9998846054077148,"intent_response_key":"faq\\/quien_eres"},{"confidence":0.00011115259258076549,"intent_response_key":"faq\\/eres_una_maquina"},{"confidence":3.869924967148108e-6,"intent_response_key":"faq\\/que_haces"},{"confidence":2.9273201107571367e-7,"intent_response_key":"faq\\/quien_te_creo"}]}}},"latest_event_time":1674691191.816772,"followup_action":null,"paused":false,"events":[{"event":"action","timestamp":1674691073.017885,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"session_started","timestamp":1674691073.017911,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"}},{"event":"action","timestamp":1674691073.017927,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1674691073.577591,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\/saludo","parse_data":{"intent":{"name":"saludo","confidence":1.0},"entities":[],"text":"\\/saludo","message_id":"ad1ecbe20d344a178824d18e72cf1ca6","metadata":{},"intent_ranking":[{"name":"saludo","confidence":1.0}]},"input_channel":"socketio","message_id":"ad1ecbe20d344a178824d18e72cf1ca6"},{"event":"user_featurization","timestamp":1674691073.951921,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"use_text_for_featurization":false},{"event":"action","timestamp":1674691073.951943,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"utter_saludo_inicial","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"bot","timestamp":1674691073.951992,"metadata":{"utter_action":"utter_saludo_inicial","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\u00a1Hola!\\ud83d\\udc4b Soy Pok\\u00e9bot y ser\\u00e9 tu nueva Pokedex \\ud83d\\udcbb","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691073.972207,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"user_name_form","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"active_loop","timestamp":1674691073.9722502,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"user_name_form"},{"event":"slot","timestamp":1674691073.972255,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"user_name","value":null},{"event":"slot","timestamp":1674691073.972258,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"counter","value":1},{"event":"slot","timestamp":1674691073.9722612,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"requested_slot","value":"user_name"},{"event":"bot","timestamp":1674691073.9722629,"metadata":{"utter_action":"utter_ask_user_name","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"Por favor, ingresa tu nombre para continuar:","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691073.978493,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"user","timestamp":1674691081.553917,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"jorge","parse_data":{"intent":{"name":"intent_pokemon_name","confidence":1.0},"entities":[{"entity":"PER","value":"jorge","start":0,"confidence":null,"end":5,"extractor":"SpacyEntityExtractor"},{"entity":"pokemon_name","start":0,"end":5,"confidence_entity":0.9999792575836182,"value":"jorge","extractor":"DIETClassifier"}],"text":"jorge","message_id":"450e86262ab449dabe37fc1031c0514f","metadata":{},"text_tokens":[[0,5]],"intent_ranking":[{"name":"intent_pokemon_name","confidence":1.0},{"name":"buscar_pokemon","confidence":3.657081658909282e-22},{"name":"faq","confidence":2.4247006860144365e-22},{"name":"despedida","confidence":1.5010465499384586e-22},{"name":"saludo","confidence":9.504542022723599e-23},{"name":"extraer_entidad","confidence":4.3269651740096674e-23}],"response_selector":{"all_retrieval_intents":["faq"],"default":{"response":{"responses":[{"text":"Soy Pok\\u00e9bot y estoy preparado para ser tu nueva Pokedex \\ud83d\\udcbb"}],"confidence":0.7264752984046936,"intent_response_key":"faq\\/quien_eres","utter_action":"utter_faq\\/quien_eres"},"ranking":[{"confidence":0.7264752984046936,"intent_response_key":"faq\\/quien_eres"},{"confidence":0.15705829858779907,"intent_response_key":"faq\\/quien_te_creo"},{"confidence":0.06720512360334396,"intent_response_key":"faq\\/que_haces"},{"confidence":0.049261294305324554,"intent_response_key":"faq\\/eres_una_maquina"}]}}},"input_channel":"socketio","message_id":"450e86262ab449dabe37fc1031c0514f"},{"event":"slot","timestamp":1674691081.5541508,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name","value":"jorge"},{"event":"user_featurization","timestamp":1674691081.572918,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"use_text_for_featurization":false},{"event":"action","timestamp":1674691081.57293,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"user_name_form","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"slot","timestamp":1674691081.5729432,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"user_name","value":"jorge"},{"event":"slot","timestamp":1674691081.5729458,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"counter","value":0},{"event":"slot","timestamp":1674691081.572948,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"requested_slot","value":null},{"event":"active_loop","timestamp":1674691081.5729501,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":null},{"event":"action","timestamp":1674691081.5779688,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"utter_menu","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"bot","timestamp":1674691081.578007,"metadata":{"utter_action":"utter_menu","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\u00a1Muy bien, jorge! Elige una de estas opciones para poder ayudarte:","data":{"elements":null,"quick_replies":null,"buttons":[{"title":"Buscar un pokemon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}],"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691081.5829902,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"user","timestamp":1674691086.317167,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\/buscar_pokemon","parse_data":{"intent":{"name":"buscar_pokemon","confidence":1.0},"entities":[],"text":"\\/buscar_pokemon","message_id":"9ab94a7cb302466a97b5605697c01c28","metadata":{},"intent_ranking":[{"name":"buscar_pokemon","confidence":1.0}]},"input_channel":"socketio","message_id":"9ab94a7cb302466a97b5605697c01c28"},{"event":"user_featurization","timestamp":1674691086.3440168,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"use_text_for_featurization":false},{"event":"action","timestamp":1674691086.3440309,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name_form","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"active_loop","timestamp":1674691086.344078,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name_form"},{"event":"slot","timestamp":1674691086.3440828,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name","value":null},{"event":"slot","timestamp":1674691086.3440871,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"counter","value":1},{"event":"slot","timestamp":1674691086.344089,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name","value":null},{"event":"slot","timestamp":1674691086.344091,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"counter","value":1},{"event":"slot","timestamp":1674691086.3440928,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"requested_slot","value":"pokemon_name"},{"event":"bot","timestamp":1674691086.344096,"metadata":{"utter_action":"utter_ask_pokemon_name","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"Escribe el nombre del pokemon que est\\u00e1s buscando \\ud83d\\udd0e","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691086.350058,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"user","timestamp":1674691093.439475,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"magnemite","parse_data":{"intent":{"name":"intent_pokemon_name","confidence":1.0},"entities":[{"entity":"PER","value":"magnemite","start":0,"confidence":null,"end":9,"extractor":"SpacyEntityExtractor"},{"entity":"pokemon_name","start":0,"end":9,"confidence_entity":0.9999827146530151,"value":"magnemite","extractor":"DIETClassifier"}],"text":"magnemite","message_id":"b1e626d405ca46e2b40e16c90bf88b47","metadata":{},"text_tokens":[[0,9]],"intent_ranking":[{"name":"intent_pokemon_name","confidence":1.0},{"name":"buscar_pokemon","confidence":3.4056945338271606e-22},{"name":"faq","confidence":2.0501851216195436e-22},{"name":"despedida","confidence":9.812310740641421e-23},{"name":"saludo","confidence":9.60807149683608e-23},{"name":"extraer_entidad","confidence":4.999436279096923e-23}],"response_selector":{"all_retrieval_intents":["faq"],"default":{"response":{"responses":[{"text":"Soy Pok\\u00e9bot y estoy preparado para ser tu nueva Pokedex \\ud83d\\udcbb"}],"confidence":0.982119083404541,"intent_response_key":"faq\\/quien_eres","utter_action":"utter_faq\\/quien_eres"},"ranking":[{"confidence":0.982119083404541,"intent_response_key":"faq\\/quien_eres"},{"confidence":0.013533945195376873,"intent_response_key":"faq\\/eres_una_maquina"},{"confidence":0.002669860841706395,"intent_response_key":"faq\\/quien_te_creo"},{"confidence":0.0016770937945693731,"intent_response_key":"faq\\/que_haces"}]}}},"input_channel":"socketio","message_id":"b1e626d405ca46e2b40e16c90bf88b47"},{"event":"slot","timestamp":1674691093.4397051,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name","value":"magnemite"},{"event":"user_featurization","timestamp":1674691093.459137,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"use_text_for_featurization":false},{"event":"action","timestamp":1674691093.459151,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name_form","policy":"RulePolicy","confidence":1.0,"action_text":null,"hide_rule_turn":true},{"event":"slot","timestamp":1674691093.459164,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_name","value":"magnemite"},{"event":"slot","timestamp":1674691093.459167,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"counter","value":0},{"event":"slot","timestamp":1674691093.459169,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"requested_slot","value":null},{"event":"active_loop","timestamp":1674691093.459171,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":null},{"event":"action","timestamp":1674691093.633418,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_informacion_pokemon","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"slot","timestamp":1674691093.633436,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"abilities_num","value":"Tiene 3 habilidades"},{"event":"slot","timestamp":1674691093.633444,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_abilities","value":"magnet-pull, sturdy y analytic."},{"event":"slot","timestamp":1674691093.633446,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"pokemon_type","value":"es de los tipos: electric y steel."},{"event":"action","timestamp":1674691093.640322,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"utter_respuesta_informacion_pokemon","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"bot","timestamp":1674691093.640363,"metadata":{"utter_action":"utter_respuesta_informacion_pokemon","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\u00a1Muy bien! magnemite es de los tipos: electric y steel. Tiene 3 habilidades: magnet-pull, sturdy y analytic.","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691093.6479669,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"utter_reingreso_menu","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"bot","timestamp":1674691093.648011,"metadata":{"utter_action":"utter_reingreso_menu","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\u00bfQu\\u00e9 deseas hacer ahora?","data":{"elements":null,"quick_replies":null,"buttons":[{"title":"Quiero buscar informaci\\u00f3n de otro pok\\u00e9mon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}],"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691093.654986,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1674691108.913601,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\/despedida","parse_data":{"intent":{"name":"despedida","confidence":1.0},"entities":[],"text":"\\/despedida","message_id":"a5d372fd09934c868e298f51d5c873f8","metadata":{},"intent_ranking":[{"name":"despedida","confidence":1.0}]},"input_channel":"socketio","message_id":"a5d372fd09934c868e298f51d5c873f8"},{"event":"user_featurization","timestamp":1674691108.926068,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"use_text_for_featurization":false},{"event":"action","timestamp":1674691108.926081,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"utter_despedida","policy":"TEDPolicy","confidence":0.9852479696273804,"action_text":null,"hide_rule_turn":false},{"event":"bot","timestamp":1674691108.926118,"metadata":{"utter_action":"utter_despedida","model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"\\u00a1Ojal\\u00e1 verte pronto!\\ud83e\\udd1a Adi\\u00f3s, jorge.","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null}},{"event":"action","timestamp":1674691108.9330041,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"name":"action_listen","policy":"TEDPolicy","confidence":0.9792237281799316,"action_text":null,"hide_rule_turn":false},{"event":"user","timestamp":1674691191.803784,"metadata":{"model_id":"bf8081e4162045d18795cd6756af93ec"},"text":"ma\\u00f1ana a las 5 de la tarde","parse_data":{"intent":{"name":"extraer_entidad","confidence":0.9984897375106812},"entities":[{"start":0,"end":26,"text":"ma\\u00f1ana a las 5 de la tarde","value":"2023-01-26T17:00:00.000-03:00","confidence":1.0,"additional_info":{"values":[{"value":"2023-01-26T17:00:00.000-03:00","grain":"hour","type":"value"}],"value":"2023-01-26T17:00:00.000-03:00","grain":"hour","type":"value"},"entity":"time","extractor":"DucklingEntityExtractor"}],"text":"ma\\u00f1ana a las 5 de la tarde","message_id":"4bf1d57d8cb24beeae7e12b08d5edc32","metadata":{},"text_tokens":[[0,6],[7,8],[9,12],[13,14],[15,17],[18,20],[21,26]],"intent_ranking":[{"name":"extraer_entidad","confidence":0.9984897375106812},{"name":"buscar_pokemon","confidence":0.0009006547625176609},{"name":"despedida","confidence":0.0004401695914566517},{"name":"faq","confidence":9.167664393316954e-5},{"name":"intent_pokemon_name","confidence":6.61602898617275e-5},{"name":"saludo","confidence":1.159783005277859e-5}],"response_selector":{"all_retrieval_intents":["faq"],"default":{"response":{"responses":[{"text":"Soy Pok\\u00e9bot y estoy preparado para ser tu nueva Pokedex \\ud83d\\udcbb"}],"confidence":0.9998846054077148,"intent_response_key":"faq\\/quien_eres","utter_action":"utter_faq\\/quien_eres"},"ranking":[{"confidence":0.9998846054077148,"intent_response_key":"faq\\/quien_eres"},{"confidence":0.00011115259258076549,"intent_response_key":"faq\\/eres_una_maquina"},{"confidence":3.869924967148108e-6,"intent_response_key":"faq\\/que_haces"},{"confidence":2.9273201107571367e-7,"intent_response_key":"faq\\/quien_te_creo"}]}}},"input_channel":"socketio","message_id":"4bf1d57d8cb24beeae7e12b08d5edc32"},{"event":"user_featurization","timestamp":1674691191.816772,"use_text_for_featurization":false}],"latest_input_channel":"socketio","active_loop":{},"latest_action":{"action_name":"action_listen"},"latest_action_name":"action_listen"},"domain":{"version":"3.1","intents":["buscar_pokemon","despedida","extraer_entidad",{"faq":{"used_entities":["PER","duration","number","pokemon_name","time","url"],"is_retrieval_intent":true}},"intent_pokemon_name","saludo"],"entities":["PER","number","time","url","duration","pokemon_name"],"actions":["action_informacion_pokemon","action_mostrar_entidades","utter_faq","validate_pokemon_name_form","validate_user_name_form"],"slots":{"user_name":{"type":"text","influence_conversation":false,"mappings":[{"type":"custom","conditions":[{"active_loop":"user_name_form","requested_slot":"user_name"}]}]},"pokemon_name":{"type":"text","influence_conversation":false,"mappings":[{"type":"from_entity","entity":"pokemon_name"}]},"pokemon_type":{"type":"text","influence_conversation":false,"mappings":[{"type":"custom"}]},"abilities_num":{"type":"text","influence_conversation":false,"mappings":[{"type":"custom"}]},"pokemon_abilities":{"type":"text","influence_conversation":false,"mappings":[{"type":"custom"}]},"counter":{"type":"float","initial_value":0,"influence_conversation":false,"mappings":[{"type":"custom"}]}},"forms":{"user_name_form":{"required_slots":["user_name"]},"pokemon_name_form":{"required_slots":["pokemon_name"]}},"responses":{"utter_saludo_inicial":[{"text":"\\u00a1Hola!\\ud83d\\udc4b Soy Pok\\u00e9bot y ser\\u00e9 tu nueva Pokedex \\ud83d\\udcbb"}],"utter_ask_user_name":[{"text":"Por favor, ingresa tu nombre para continuar:"}],"utter_menu":[{"text":"\\u00a1Muy bien, {user_name}! Elige una de estas opciones para poder ayudarte:","buttons":[{"title":"Buscar un pokemon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}]}],"utter_ask_pokemon_name":[{"text":"Escribe el nombre del pokemon que est\\u00e1s buscando \\ud83d\\udd0e"}],"utter_despedida":[{"text":"\\u00a1Ojal\\u00e1 verte pronto!\\ud83e\\udd1a Adi\\u00f3s, {user_name}."}],"utter_reingreso_menu":[{"text":"\\u00bfQu\\u00e9 deseas hacer ahora?","buttons":[{"title":"Quiero buscar informaci\\u00f3n de otro pok\\u00e9mon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}]}],"utter_respuesta_informacion_pokemon":[{"text":"\\u00a1Muy bien! {pokemon_name} {pokemon_type} {abilities_num}: {pokemon_abilities}"},{"text":"\\u00a1Excelente! {pokemon_name} {pokemon_type} {abilities_num}: {pokemon_abilities}"},{"text":"\\u00a1Perfecto! {pokemon_name} {pokemon_type} {abilities_num}: {pokemon_abilities}"},{"text":"\\u00a1Mira lo que encontr\\u00e9! {pokemon_name} {pokemon_type} {abilities_num}: {pokemon_abilities}"}],"utter_faq\\/quien_eres":[{"text":"Soy Pok\\u00e9bot y estoy preparado para ser tu nueva Pokedex \\ud83d\\udcbb"}],"utter_faq\\/quien_te_creo":[{"text":"Fui creado por Mahmut\\ud83e\\udd13, un ling\\u00fcista computacional chileno \\ud83c\\udde8\\ud83c\\uddf1"}],"utter_faq\\/eres_una_maquina":[{"text":"S\\u00ed, soy un chatbot basado en tecnolog\\u00edas de NLP e Inteligencia Artificial"}],"utter_faq\\/que_haces":[{"text":"Por el momento, puedo ayudarte a buscar informaci\\u00f3n de un pok\\u00e9mon si me dices su nombre. \\u00bfQu\\u00e9 te gustar\\u00eda hacer?","buttons":[{"title":"Quiero buscar informaci\\u00f3n de un pok\\u00e9mon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}]}],"utter_default_fallback":[{"text":"Lo lamento, no pude entender tu mensaje. Intenta dec\\u00edrmelo de otra forma o escoge una de mis opciones:","buttons":[{"title":"Quiero buscar informaci\\u00f3n de un pok\\u00e9mon","payload":"\\/buscar_pokemon"},{"title":"Quiero terminar la conversaci\\u00f3n","payload":"\\/despedida"}]}]},"session_config":{"session_expiration_time":60,"carry_over_slots_to_new_session":true}},"version":"3.4.1"}}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 874, in _run_action
    events = await action.run(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/action.py", line 765, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'action_mostrar_entidades'
2023-01-25 21:00:22,418 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-170' coro=<AsyncServer._handle_event_internal() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py:506> exception=AttributeError("'list' object has no attribute 'strip'")>
Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 508, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/socketio/asyncio_server.py", line 542, in _trigger_event
    ret = await handler(*args)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/socketio.py", line 268, in handle_message
    await on_new_message(message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in handler
    await app.ctx.agent.handle_message(message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/agent.py", line 420, in handle_message
    return await self.processor.handle_message(  # type: ignore[union-attr]
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 149, in handle_message
    await self._run_prediction_loop(message.output_channel, tracker)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 774, in _run_prediction_loop
    should_predict_another_action = await self._run_action(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 909, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 801, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 817, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 233, in send_response
    await self.send_text_message(recipient_id, message.pop("text"), **message)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/channels/socketio.py", line 60, in send_text_message
    for message_part in text.strip().split("\n\n"):
AttributeError: 'list' object has no attribute 'strip'
2023-01-25 21:03:55,441 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=fq7W21N3mg_26lviAAAA'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 21:03:56,199 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<AsyncServer._service_task() running at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f902c83f0d0>()]>>
2023-01-25 21:03:56,200 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-381' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8f90faf5b0>()]>>
2023-01-25 21:10:45,079 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-01-25 21:10:48,298 [INFO ]  Loading model models/20230125-205103-curious-quarter.tar.gz...
2023-01-25 21:10:50,325 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 21:10:55,937 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 21:11:46,876 [WARNI]  The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2023-01-25 21:11:56,269 [INFO ]  Rasa server is up and running.
2023-01-25 21:12:04,988 [ERROR]  Failed to run custom action 'validate_user_name_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connection refused]
2023-01-25 21:12:04,988 [ERROR]  Encountered an exception while running action 'user_name_form'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "uvloop/loop.pyx", line 1974, in create_connection
  File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/action.py", line 741, in run
    response: Any = await self.action_endpoint.request(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 164, in request
    async with session.request(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5055 ssl:default [Connection refused]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/processor.py", line 874, in _run_action
    events = await action.run(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/loops.py", line 33, in run
    events += await self.do(output_channel, nlg, tracker, domain, events)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/forms.py", line 635, in do
    events = await self._validate_if_required(tracker, domain, output_channel, nlg)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/forms.py", line 542, in _validate_if_required
    return await self.validate(tracker, domain, output_channel, nlg)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/forms.py", line 394, in validate
    validation_events = await self.validate_slots(
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/forms.py", line 272, in validate_slots
    validate_events = await _action.run(output_channel, nlg, _tracker, domain)
  File "/Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/rasa/core/actions/action.py", line 776, in run
    raise RasaException(
rasa.shared.exceptions.RasaException: Failed to execute custom action 'validate_user_name_form'. Couldn't connect to the server at 'http://localhost:5055/webhook.
2023-01-25 21:12:45,234 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=gFWD2FhPzBrzthDMAAAA'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 21:12:45,809 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-51' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff3521f0a60>()]>>
2023-01-25 21:12:45,810 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<AsyncServer._service_task() running at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff35c3af3a0>()]>>
2023-01-25 21:13:31,327 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-01-25 21:13:34,526 [INFO ]  Loading model models/20230125-205103-curious-quarter.tar.gz...
2023-01-25 21:13:36,540 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 21:13:40,293 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 21:14:28,104 [WARNI]  The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2023-01-25 21:14:37,193 [INFO ]  Rasa server is up and running.
2023-01-25 22:04:36,319 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=41HiHq89WEZ_94UcAAAA'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:04:36,325 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=jfGSdKudbDMZpzc-AAAC'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:04:38,021 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<AsyncServer._service_task() running at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f98314b8610>()]>>
2023-01-25 22:04:38,021 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-1918' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f98314b8370>()]>>
2023-01-25 22:04:38,021 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-1930' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f98307d7fa0>()]>>
2023-01-25 22:38:23,314 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-01-25 22:38:26,682 [INFO ]  Loading model models/20230125-220506-tender-layout.tar.gz...
2023-01-25 22:38:28,759 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 22:38:34,648 [INFO ]  Trying to load SpaCy model with name 'es_core_news_lg'.
2023-01-25 22:39:27,027 [WARNI]  The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future ðŸ”¬ Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2023-01-25 22:39:37,137 [INFO ]  Rasa server is up and running.
2023-01-25 22:42:31,201 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=OYX9OtC5oJufrcYJAAAA'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:43:10,104 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=oPg4MkaS3X7-lqC5AAAE'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:52:02,307 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=kh7u3UZA-p2CqtNtAAAC'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:56:20,732 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=7Gtuqj7LOzTw8Gt0AAAG'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:56:20,734 [ERROR]  Exception occurred while handling uri: 'ws://localhost:5005/socket.io/?EIO=4&transport=websocket&sid=PXsOC7SL0DrAbFVoAAAI'
Traceback (most recent call last):
  File "handle_request", line 124, in handle_request
sanic.exceptions.ServerError: Invalid response type None (need HTTPResponse)
2023-01-25 22:56:22,288 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<AsyncServer._service_task() running at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_server.py:498> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc3e023be80>()]>>
2023-01-25 22:56:22,288 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-912' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc3e00a1b80>()]>>
2023-01-25 22:56:22,288 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-921' coro=<AsyncSocket.schedule_ping.<locals>.send_ping() done, defined at /Users/mahtiasmunoz/opt/anaconda3/envs/rasavenv/lib/python3.8/site-packages/engineio/asyncio_socket.py:125> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc3e02cfbe0>()]>>
